In [1]:
data=pd.DataFrame({'A':[1,2,4,1,2,4],
                   'b':[4,5,6,7,8,9],
                   'c':[0,0,0,0,0,0],
                   'd':[1,1,1,1,1,1]})

In [2]:
data

   A  b  c  d
0  1  4  0  1
1  2  5  0  1
2  4  6  0  1
3  1  7  0  1
4  2  8  0  1
5  4  9  0  1

In [10]:
from sklearn.feature_selection import VarianceThreshold
var_thres=VarianceThreshold(threshold=0)
var_thres.fit(data)

VarianceThreshold(threshold=0)

In [11]:
var_thres.get_support()

array([ True,  True, False, False])

In [12]:
data.columns[var_thres.get_support()]

Index(['A', 'b'], dtype='object')

In [13]:
constant_columns=[columns for columns in data.columns if columns not in data.columns[var_thres.get_support()]]
print(len(constant_columns))
print(constant_columns)

2
['c', 'd']

In [14]:
for feature in constant_columns:
    print(feature)

c
d

In [15]:
data.drop(constant_columns,axis=1)

   A  b
0  1  4
1  2  5
2  4  6
3  1  7
4  2  8
5  4  9

In [21]:
df=pd.read_csv('train.csv',nrows=1000)

In [22]:
df.shape

(1000, 371)

In [23]:
df.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3       var38  TARGET
0   1     2     23  ...                     0.0   39205.170       0
1   3     2     34  ...                     0.0   49278.030       0
2   4     2     23  ...                     0.0   67333.770       0
3   8     2     37  ...                     0.0   64007.970       0
4  10     2     39  ...                     0.0  117310.979       0

[5 rows x 371 columns]

In [28]:
x=df.drop(['TARGET'], axis=1)
y=df['TARGET']

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [32]:
x_train.shape,x_test.shape

((700, 370), (300, 370))

In [33]:
var_thres.fit(x_train)

VarianceThreshold(threshold=0)

In [35]:
sum(var_thres.get_support())

233

In [36]:
len(x_train.columns[var_thres.get_support()])

233

In [38]:
constant_columns = [columns for columns in x_train.columns if columns not in x_train.columns[var_thres.get_support()]]
print(len(constant_columns))

137

In [39]:
for column in constant_columns:
    print(column)

imp_op_var40_efect_ult1
ind_var2_0
ind_var2
ind_var6_0
ind_var6
ind_var13_medio_0
ind_var13_medio
ind_var14
ind_var18_0
ind_var18
ind_var27_0
ind_var28_0
ind_var28
ind_var27
ind_var29_0
ind_var29
ind_var32_cte
ind_var32_0
ind_var32
ind_var33_0
ind_var33
ind_var34_0
ind_var34
ind_var41
ind_var46_0
ind_var46
num_var6_0
num_var6
num_var13_medio_0
num_var13_medio
num_var14
num_var18_0
num_var18
num_var27_0
num_var28_0
num_var28
num_var27
num_var29_0
num_var29
num_var32_0
num_var32
num_var33_0
num_var33
num_var34_0
num_var34
num_var41
num_var46_0
num_var46
saldo_var6
saldo_var13_medio
saldo_var14
saldo_var18
saldo_var28
saldo_var27
saldo_var29
saldo_var32
saldo_var33
saldo_var34
saldo_var41
saldo_var46
delta_imp_amort_var18_1y3
delta_imp_amort_var34_1y3
delta_imp_aport_var33_1y3
delta_imp_reemb_var17_1y3
delta_imp_reemb_var33_1y3
delta_imp_trasp_var17_out_1y3
delta_imp_trasp_var33_in_1y3
delta_imp_trasp_var33_out_1y3
delta_num_aport_var33_1y3
delta_num_reemb_var17_1y3
delta_num_reemb_var33_1y3
delta_num_trasp_var17_out_1y3
delta_num_trasp_var33_in_1y3
delta_num_trasp_var33_out_1y3
imp_amort_var18_hace3
imp_amort_var18_ult1
imp_amort_var34_hace3
imp_amort_var34_ult1
imp_aport_var13_ult1
imp_aport_var17_hace3
imp_aport_var33_hace3
imp_aport_var33_ult1
imp_var7_emit_ult1
imp_compra_var44_ult1
imp_reemb_var13_hace3
imp_reemb_var17_hace3
imp_reemb_var17_ult1
imp_reemb_var33_hace3
imp_reemb_var33_ult1
imp_trasp_var17_in_hace3
imp_trasp_var17_out_hace3
imp_trasp_var17_out_ult1
imp_trasp_var33_in_hace3
imp_trasp_var33_in_ult1
imp_trasp_var33_out_hace3
imp_trasp_var33_out_ult1
imp_venta_var44_hace3
ind_var7_emit_ult1
num_var2_0_ult1
num_var2_ult1
num_aport_var13_ult1
num_aport_var17_hace3
num_aport_var33_hace3
num_aport_var33_ult1
num_var7_emit_ult1
num_compra_var44_ult1
num_meses_var13_medio_ult3
num_meses_var29_ult3
num_meses_var33_ult3
num_op_var40_efect_ult1
num_reemb_var13_hace3
num_reemb_var17_hace3
num_reemb_var17_ult1
num_reemb_var33_hace3
num_reemb_var33_ult1
num_trasp_var17_in_hace3
num_trasp_var17_out_hace3
num_trasp_var17_out_ult1
num_trasp_var33_in_hace3
num_trasp_var33_in_ult1
num_trasp_var33_out_hace3
num_trasp_var33_out_ult1
num_venta_var44_hace3
saldo_var2_ult1
saldo_medio_var13_medio_hace2
saldo_medio_var13_medio_hace3
saldo_medio_var13_medio_ult1
saldo_medio_var13_medio_ult3
saldo_medio_var17_hace3
saldo_medio_var29_hace2
saldo_medio_var29_hace3
saldo_medio_var29_ult1
saldo_medio_var29_ult3
saldo_medio_var33_hace2
saldo_medio_var33_hace3
saldo_medio_var33_ult1
saldo_medio_var33_ult3

In [40]:
x_train.drop(constant_columns,axis=1)

       ID  var3  ...  saldo_medio_var44_ult3      var38
105   195     2  ...                     0.0   93861.78
68    144     2  ...                     0.0  165258.42
479   965     2  ...                     0.0   61653.75
399   798     2  ...                     0.0  119707.20
434   864     2  ...                     0.0  109607.01
..    ...   ...  ...                     ...        ...
835  1660     2  ...                     0.0   45189.33
192   378     2  ...                     0.0  145599.06
629  1254     2  ...                     0.0   99613.92
559  1117     2  ...                     0.0   48869.88
684  1377     2  ...                     0.0   59889.21

[700 rows x 233 columns]